# Generated by Django 2.0.2 on 2018-03-15 16:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180307_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name="Description de l'événement"),
        ),
    ]
