# Generated by Django 2.0.2 on 2018-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180307_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name="Lien associé à l'évènement"),
        ),
    ]
