# Generated by Django 2.0.2 on 2018-03-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180307_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Nom de l'asso")),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='asso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Asso'),
        ),
    ]
