# Generated by Django 2.0.2 on 2018-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180307_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name="Description de l'événement"),
        ),
    ]
