# Generated by Django 2.0.2 on 2018-03-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180327_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(max_length=1000, verbose_name='URL de la photo associée'),
        ),
    ]
