# Generated by Django 2.0.2 on 2018-03-21 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180315_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, verbose_name="Description de l'événement"),
        ),
    ]
