# Generated by Django 2.0.2 on 2018-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180321_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=10, verbose_name="Prix de l'évènement"),
        ),
    ]
