# Generated by Django 2.0.2 on 2018-03-21 13:39

from django.db import migrations, models
import events.validations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180321_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=1000, validators=[events.validations.validate_event], verbose_name="Lien associé à l'évènement"),
        ),
    ]
