# Generated by Django 2.0.2 on 2018-03-28 17:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180328_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, verbose_name="Description de l'événement"),
        ),
    ]
