# Generated by Django 2.0.2 on 2018-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_userassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('b', 'En attente'), ('p', 'Publié'), ('s', 'Supprimé')], default='e', max_length=1),
            preserve_default=False,
        ),
    ]
