# Generated by Django 2.0.2 on 2018-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180329_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='association',
            new_name='asso',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('e', 'En attente'), ('p', 'Publié'), ('t', 'Terminé')], default='e', max_length=1, verbose_name='Statut de la publication'),
        ),
    ]
