# Generated by Django 2.0.2 on 2018-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180329_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('e', 'En attente'), ('p', 'Publié'), ('t', 'Terminé'), ('s', 'Demande de suppression')], default='e', max_length=1, verbose_name='Statut de la publication'),
        ),
    ]
